spring.application.name=course-services
server.port=8082
spring.datasource.username=root
spring.datasource.password=linh@1010

spring.datasource.url=jdbc:mysql://localhost:3306/course_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh

# Nen khai bao them Driver de dam bao Spring Boot nhan dien dung MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# (Tuy chon) De Hibernate tu dong tao/cap nhat bang trong database
spring.jpa.hibernate.ddl-auto=update
# (Tuy chon) Hien thi cau lenh SQL de de dang debug
spring.jpa.show-sql=true
jwt.secret=Nguyenthithuylinh$10102005@123@lyn1